### ISSUE TITLE
Percentage doesn't seem to be calculated correctly after ABS region type selection 

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#101]
The new functionality for region type selection seems to be calculating percentages wrongly.  Much as I'd love for 78% of Queenslanders to have been born in NZ, I don't think that's right.  And it's not what the figures say...
![abs](https://cloud.githubusercontent.com/assets/1151940/8986444/9266ecbe-371f-11e5-93ba-e1565dc9489f.png)

**Comment by bsimyo** [comment]
It doesn't always happen. I've now got it showing more realistic figures for the same thing.  It must have been a series of selections I made trying different countries of birth and different region types.

**Comment by kgrochow** [comment]
That is just the delay in the abs service.  It can take several seconds to return a response at times and with the region selection option, there are 5x + queries to cache up before it gets snappier.  You'll notice that Australia is still showing in the feature popup as well which is what is what it is probably still on.  There need to be wait-loading gifs with this ultimately, but that is not ready yet.

**Comment by kring** [comment]
I'm able to reproduce this easily in my (slow) IE9 virtual machine by doing the following:

* Enable Country of Birth data set.
* Switch Region Type to "States and Territories"
* Turn on "New Zealand"
* Turn off "Australia"
* Double click on Australia to turn it on and then immediately back off.

The UI shows Australia unchecked, but the legend, map, and feature info popup all behave as if it's checked.

I can't make this happen on my faster machine, presumably because it's a race condition and I can't double click fast enough.

@kgrochow I'm happy to look into this if you like, I love race conditions. :)
