### ISSUE TITLE
Add Department of Environment Protected Areas datasets

### ISSUE THREAD

**Issue by kring** [NICTA/nationalmap#122]
AREMI has these already:
http://github.com/NICTA/aremi-natmap/blob/2015-09-25/datasources/aremi/custodian/Department_of_Environment/Protected_Areas.ejs

**Comment by bsimyo** [comment]
According to Dmitar at GA, this should use the new data services released by Dept of Env in Oct at http://www.environment.gov.au/about-us/environmental-information-data/web-services

**Comment by meh9** [comment]
Protected_Areas.ejs are actually the GA hosted layers that Dmitar has asked that we move away from.

The new layers hosted by the DoE can be found in these two files:

https://github.com/NICTA/aremi-natmap/blob/master/datasources/aremi/custodian/Department_of_Environment/Commonwealth_Marine_Regions.ejs

https://github.com/NICTA/aremi-natmap/blob/master/datasources/aremi/custodian/Department_of_Environment/Web_Services.ejs

Note that they are still a little rough perhaps - for instance, I've not completed the WFS URL's for any of these yet, but might get around to that today.

The layer `Strategic Assessment Areas` is also missing since it currently does not work.

**Comment by RacingTadpole** [comment]
@meh9 - There are three web services on http://www.environment.gov.au/about-us/environmental-information-data/web-services that are not listed in the AREMI files:
- Environmental Offsets secured under Part 9 of the EPBC Act
- Strategic Assessment areas
- Conservation Management Zones of Australia

Is there a reason they were left out of AREMI? (perhaps they are recent additions?)

**Comment by meh9** [comment]
Offsets were withdrawn for licensing reasons, but not removed from the web page, and as you saw the other doesn't work - I've notified them of both these issues some time ago.

The last one is new to me, will make a task to add it to AREMI.
