### ISSUE TITLE
Change support email address

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#123]
Should be changed from nationalmap@communications.gov.au to nationalmap@pmc.gov.au in the next release.

**Comment by bsimyo** [comment]
Actually the new address should be data@pmc.gov.au

**Comment by bsimyo** [comment]
Note - this applies to all email addresses in NM (including for support, for more info, for data custodians etc)

**Comment by kring** [comment]
I'll also be changing all mentions of "Department of Communications" to "Department of the Prime Minister and Cabinet", except the copyright at the bottom of each of the help pages, which will change to:

> © Department of the Prime Minister and Cabinet, Department of Communications, and National ICT Australia Limited (NICTA) 2014-2015. All Rights Reserved.

Our [privacy page](http://nationalmap.gov.au/privacy.html) links to the [DoC privacy policy](https://www.communications.gov.au/privacy-policy).  I'll leave that in place because I don't see an obvious equivalent on the PM&C website.
