### ISSUE TITLE
Add ASRIS soil map data

### ISSUE THREAD

**Issue by stevage** [NICTA/nationalmap#128]
Lots of good layers here: http://www.clw.csiro.au/aclep/soilandlandscapegrid/GetData-GIS.html

**Comment by RacingTadpole** [comment]
I see we can add these individually using URLs such as http://www.asris.csiro.au/ArcGis/rest/services/TERN/BDW_ACLEP_AU_NAT_C/MapServer .

Alternatively, we can add the whole lot in one go using: http://www.asris.csiro.au/ArcGis/rest/services/TERN . However then the subitems are given unpleasant names such as "BDW_ACLEP_AU_NAT_C", instead of "Available Water Capacity".

I am tempted to make a little code change to make this name change...

**Comment by RacingTadpole** [comment]
@kring / @stevage , for the Landscape Attributes (http://www.asris.csiro.au/ArcGis/rest/services/TERN/SRTM_attributes_3s_ACLEP_AU/MapServer), there are lots of different layers that only really make sense if you can break them all out into separate items. Is that possible? I'm currently using a json file like this:

    {
        "catalog": [
            {
                    "name": "Landscape Attributes",
                    "type": "group",
                    "items": [
                        {
                            "name": "All Available Attributes",
                            "url": "http://www.asris.csiro.au/ArcGis/rest/services/TERN/SRTM_attributes_3s_ACLEP_AU/MapServer",
                            "type": "esri-mapServer"
                        }
                    ]
            }
        ]
    }

**Comment by kring** [comment]
@RacingTadpole I'm not sure if I'm understanding your question completely, but if you set `"type": "esri-mapServer-group"`, TerriaJS will query the group for all the dynamic layers and make an item for each.
