### ISSUE TITLE
In csv-geo-au spec and code support, add in poa_code as synonym for poa

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#136]
@stevage  I see that the new csv support now doesn't recognise poa_code for ABS postal areas (which it used to support) and supports poa and poa_2011 instead.  It seems that ABS themselves often use poa_code (eg as for POAs, they distinguish between poa_name and poa_code).  Eg see http://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/1270.0.55.003Explanatory%20Notes10July%202011?OpenDocument and https://censusdata.abs.gov.au/arcgis/rest/services/2011_POA/MapServer/0 

Given that we want things to work well for unambiguous cases and that this is one, I think we should add poa_code as a synonym for poa. https://en.wikipedia.org/wiki/Robustness_principle 

As well as that, there is also backwards compatibility for people who have already been using CSVs with poa_code (including the standard csv file used in most NM demos).

**Comment by stevage** [comment]
Huh, that's odd. In our region mapping server, which has those shapefiles loaded, `POA_NAME` is exactly the same as `POA_CODE`. That is, a four digit postcode.

Anyway, I've already included `poa_code` as a synonym in the forthcoming changes in NM. You're not seeing it at the moment because in TerriaJS I disabled the excessively liberal matching of "poa*" to poa (which would have matched fields like `poachers`).

**Comment by bsimyo** [comment]
ok great.

**Comment by kring** [comment]
@stevage and @bsimyo can we close this?

**Comment by stevage** [comment]
![screenshot 2015-11-17 10 42 17](https://cloud.githubusercontent.com/assets/678344/11198295/e5228d34-8d17-11e5-9ec5-6fa29608fda6.png)

Yes.
