### ISSUE TITLE
some incorrect coordinates via Search Locations

### ISSUE THREAD

**Issue by indexgeo** [NICTA/nationalmap#140]
Do a search for "Shoalhaven Heads". The result in "Locations" will zoom to the northern hemisphere. Obviously the record has a "positive latitude" data entry mistake. Not sure what the source is for the Locations search. This indicates that its system needs a programmatic scan to validate anything with Australia in the name to be within an Australian bounding rectangle.

(Not sure where to report this, so starting here.)

**Comment by kring** [comment]
Thanks for the report!  The Locations results come from the [Bing Maps Locations REST API](https://msdn.microsoft.com/en-us/library/ff701711.aspx).  If it has bad coordinates, we'll need to report it to them.  As far as I know, the best place for that is the [Bing Maps Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=bingmapsservices).

I'm closing this since it's not something we can change directly in NationalMap.

**Comment by kring** [comment]
I reported it to the Bing Maps forum:
https://social.msdn.microsoft.com/Forums/en-US/f7e22afa-d109-408c-ae8a-51c40f4fae3b/incorrect-location-for-shoalhaven-heads?forum=bingmapsservices

**Comment by kring** [comment]
Microsoft reported back:

> Just checked our internal system and see that a fix for this has already been made. We have a major update planned for our geocoder in a few months that will correct this issue and a number of others.
