### ISSUE TITLE
Natural Resource Management (NRM) Regions (2015) not loading

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#196]
Under data.gov.au > Department of the Environment > Natural Resource Management (NRM) Regions (2015)

it gets an error.  It appears that the WMS request is coming across without a layer name?
http://www.environment.gov.au/mapping/services/ogc_services/Natural_Resource_Management_Regions/MapServer/WMSServer

Other WMS layers come across ok from Environment - eg Conservation_Management_Zones (but duplicated?)

Example at http://nationalmap.gov.au/#share=MxegIS 

![image](https://cloud.githubusercontent.com/assets/4373945/12766690/02f311d4-ca59-11e5-907d-ac4ed97c488a.png)

**Comment by stevage** [comment]
Ok, after a fair bit of digging, the cause turns out to be fairly simple. [CKAN is reporting](http://www.data.gov.au/api/3/action/package_show?id=natural-resource-management-nrm-regions-2015) the layer name is "0", but the [correct layer name](http://www.environment.gov.au/mapping/services/ogc_services/Natural_Resource_Management_Regions/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities) is "NRM Regions". So Terria looks for a layer called "0", can't find it, and quietly fails.

At the least, we should fail less quietly.

Hopefully that gives you enough information to fix the issue at your end?

**Comment by stevage** [comment]
Doh, it turns out we already do log an error message.

![screenshot 2016-02-23 15 47 26](https://cloud.githubusercontent.com/assets/678344/13242033/cade2eea-da44-11e5-809c-567bf3984cd6.png)
