### ISSUE TITLE
WFS data URL limits to 1000 features

### ISSUE THREAD

**Issue by tobybellwood** [NICTA/nationalmap#212]
Had a report from a client that their dataset download from the data URL is truncated unexpectedly.  It's because of the hard coded 1000 maxFeatures limit.  Are there any alternatives we can explore?

![image](https://cloud.githubusercontent.com/assets/4373945/13062964/4555cdd0-d497-11e5-80ef-6fc4e007b487.png)

**Comment by kring** [comment]
@tobybellwood we chose 1000 in order to provide a URL that will at least return something.  Many WFS servers will fall over or take an amazingly long time to return anything at all if asked to provide the entire dataset.  The intention (as implied in the text under Data URL) is that the user would customize the query parameters for their needs.

It would be better if we could provide a link to the actual data rather than the WFS view of it.  E.g. the dataset page on data.gov.au if there is one, or a download link for the shapefile, or something like that.

**Comment by tobybellwood** [comment]
@kring - A link to a downloadable file would be ideal.  I will investigate some options from our side.

**Comment by stevage** [comment]
Theoretically, we could batch the download and recombine it...I think?

**Comment by stevage** [comment]
In the recent NM update, we provided direct downloads (from the ABS source) for all the ASGS boundaries - although not the POA boundary in the screenshot above.

![screenshot 2016-02-17 10 56 27](https://cloud.githubusercontent.com/assets/678344/13095354/33e23d8a-d565-11e5-8116-1364ed14f05a.png)

Would simply extending this to the remaining datasets solve the problem?

**Comment by stevage** [comment]
(I did extend it as suggested above)
