### ISSUE TITLE
Allow user to find out what version of NM and TerriaJS they are using

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#24]
Requested by GA "I feel this is mandatory to ensure that when discussions on progress take place we are describing the same version of the product."

**Comment by hilarycinis** [comment]
Are GA development teams and external devs the 'user'? We'd handle that in the git repo, nothing required on the font end?

**Comment by bsimyo** [comment]
No, they want to know what version is actually deployed to production.

**Comment by hilarycinis** [comment]
We could pop a wee version number/counter alomg side the logo (replace beta) and/or make a spot for it in the About pages, up in the header (along with other important notices?) There's heaps of space.

Hilary Cinis
Principal UX & Designer
UX & Design Manager
NICTA

On 22 May 2015 6:41 pm, Bill Simpson-Young <notifications@github.com> wrote:

No, they want to know what version is actually deployed to production.

—
Reply to this email directly or view it on GitHub<https://github.com/NICTA/nationalmap/issues/24#issuecomment-104572173>.

________________________________

The information in this e-mail may be confidential and subject to legal professional privilege and/or copyright. National ICT Australia Limited accepts no liability for any damage caused by this email or its attachments.

**Comment by kgrochow** [comment]
Version number available by hovering over National Map logo in upper left.
