### ISSUE TITLE
Land -> Gravity Image dataset shows a deprecation message

### ISSUE THREAD

**Issue by kring** [NICTA/nationalmap#49]
![image](https://cloud.githubusercontent.com/assets/924374/8177574/68b73854-1449-11e5-95fe-66925cc30834.png)

**Comment by kring** [comment]
The Magnetic Image dataset does the same.

**Comment by dbutrovski** [comment]
What you see is standard notification that Geoscience Australia embeds into web services we manage ahead of their decommissioning, instead of just turning it off without notification. In this case it is a major restructure/change to the service including layer names and the service endpoint URL could not be reused. Just re-point to the replacement service as instructed above. The new service has many more layers - please see here for more detail:
http://www.ga.gov.au/gisimg/rest/services/earth_science/Geoscience_Australia_National_Geophysical_Grids/MapServer
The change will require updates to the National Data Sets curated content menu.

**Comment by kring** [comment]
Thanks @dbutrovski, we will do that before the end of the month.

**Comment by kring** [comment]
Fixed by #69
