### ISSUE TITLE
Update privacy statement to be Australian Government one

### ISSUE THREAD

**Issue by bsimyo** [NICTA/nationalmap#54]

**Comment by stevage** [comment]
Text to include:

NationalMap Website Privacy Notice

The Department of Communications is covered by the Privacy Act 1988 (Cth) (‘the Privacy Act’). The 
Privacy Act contains 13 Australian Privacy Principles (‘the APPs’) which governs how Australian 
Government agencies should collect, use, store and disclose personal information, and how 
individuals can access records containing their personal information.  General information about the 
Privacy Act and the APPs can be found on the website of the Office of the Australian Information 
We are committed to protecting your privacy. Our Privacy Policy can be accessed via this link. The 
NationalMap website (this website) complies with the Australian Information Commissioner’s APP 
Guidelines and with our APP Privacy Policy.
You are reminded that there are risks involved in sending information over the internet.
Any data collected by us as described in this notice is stored securely, and archived for a period of at 
least five years, and possible up to ten years.
We only use personal information that we collect through this website for the purposes for which it 
was given to us or for related purposes, such as the maintenance, upgrade or improvements of this 
website or any policy development associated with this website. 
We do not share personal information about any individual which we collect through this website to 
any third party, such as other Australian Government agencies or organisations unless one of the 
 the individual has consented;
 the individual would reasonably expect, or has been told that information of that kind is 
usually passed to those other individuals, agencies, organisations;
 is required or authorised by law;
 a Permitted General Situation (as defined under section 16A of the Privacy Act) exists (for 
example, it will prevent or lessen a serious and imminent threat to somebody’s life or 
 the disclosure is reasonably necessary for the enforcement of the criminal law or of a law 
imposing a pecuniary penalty, or for the protection of public revenue.
Information logged when browsing the NationalMap website
We do not collect personal information about you if you only browse this website.
When you browse this website, our server logs the following information:
 the type of browser and operating system you are using;
 the address of the referring site (for example, the previous site that you visited); and
 your IP (Internet Protocol) address, which is a number unique to the machine on which you 
connect to the internet.
Our server also logs the following information:
 the date and time of your visit; and
 the address of the pages accessed and the documents downloaded.
We use the information we collect from your browsing of this website for statistical analysis, system 
administration, monitoring of this website’s security, customisation of this website to users’ needs, 
and the evaluation, research and development of this website.
No attempt will be made to identify users due to their browsing activities on this website, except in 
the unlikely event of an investigation, for example, where a law enforcement agency may exercise a 
warrant or subpoena.  The information we collect from your browsing of this website will only be
disclosed to a third party if it is required or authorised by law.
A cookie is an electronic token that is passed to your browser and your browser passes it back to the 
server whenever a page is sent to you.
For this website, our server creates a cookie that is used to keep track of the pages you have 
accessed. This cookie allows you to page back and forward through this website and return to pages 
you have already visited. This cookie exists only for the time that you are accessing our server.
Please note that some browsers can be configured to allow cookies to be accessed by servers other 
than the originating server. Most browsers can also be configured to notify the user when a cookie is 
received, allowing you to either accept or reject it. You do not need to have configured your browser 
to enable the accepting or sending of cookies in order to use this website.
Cookies are not used for any other purposes on this website, for example, we do not use cookies on 
this website to collect your personal information.
Online forms, email address and contact us
When using this website (for example, the online forms or contact us function), you may provide us 
with your personal information, for example, your name and email address etc. When you do this, 
you agree to provide us with your consent to disclose your personal information to other areas of 
the Department and potentially other appropriate third parties, for example, the National ICT 
Australia, Geoscience Australia, Bureau of Meteorology, Australian Bureau of Statistics, data.gov.au 
website etc. so that we can appropriately respond to your request or query.  You also agree to 
provide us with your consent to disclose your personal information for the administration, 
regulation and evaluation processes associated with this website or for related purposes such as any 
policy development associated with this website.
You have the right not to identify yourself or to use an alias (pseudonym) when you contact us or 
use online forms in relation to this website.  However, where it is impractical for us to deal with your 
request in that way, or the law requires or authorise us to collect your personal information, then 
we may require you to identify yourself.
The search terms that you enter when using this website’s search engine are collected so that we 
can find out what users are looking for on this website.
This website contains links to other websites for the attribution of the data source or may use social 
media sites to make it easy to share information.  These other sites may use web measurement 
tools, customisation technologies and persistent cookies to inform the services that they provide to 
their users.  We are not responsible for the privacy practices or the content of other sites.  This 
website does not use, maintain or share Personally Identifiable Information made through the other 
websites, such as, Facebook, Twitter or YouTube etc.

**Comment by kring** [comment]
Where is this supposed to go in NM?  Should the "Privacy" link at the bottom of the About and Help pages go to a new page with this content maybe?

![image](https://cloud.githubusercontent.com/assets/924374/8401848/5644bc30-1e78-11e5-8189-9c46246b28d7.png)

**Comment by bsimyo** [comment]
Yes. that makes sense. I'll ask DoC to set that up which makes a lot more sense than us maintaining the DoC privacy page

**Comment by bsimyo** [comment]
DoC have pointed out that this is actually a custom privacy statement for NM and relevant to multiple agencies (not just DoC) and so it makes sense to have this hosted along with NM itself.  That makes sense.  We should have this on its own page similar to the About page. @philipgrimmett when you improve the About page, could you also make a new privacy page with this info and link to it from the "privacy" link. Thanks.

**Comment by kring** [comment]
Done in @philipgrimmett's new about page.
